name: Test VSCode Extension
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          # @todo https://github.com/actions/setup-node/pull/299
          # cache: true
      -
        run: yarn install
        working-directory: ./src/vscode-extension/drupalpod-ext
      # @todo run tests when "vscode-test" package works in GitPod and/or Actions.
      # -
      #  run: yarn test
      #  working-directory: ./src/vscode-extension/drupalpod-ext
      -
        run: yarn package
        working-directory: ./src/vscode-extension/drupalpod-ext
